### ISSUE TITLE
`encrypt.py` FFmpeg error

### ISSUE THREAD

**Issue by ILPlais** [ILPlais/binary_qrcode_stegano#2]
https://github.com/ILPlais/binary_qrcode_stegano/blob/335891177bbb916ceb81e0bc7937c3b70f44dcdd/encrypt.py#L95-L102

```
[INFO] Create an FFmpeg input stream from the video file…
[INFO] Create an FFmpeg output stream for the output video file…
[INFO] Start the FFmpeg subprocess…
ffmpeg version 5.1.2-3ubuntu1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12 (Ubuntu 12.2.0-14ubuntu2)
  configuration: --prefix=/usr --extra-version=3ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test/La vérité sur notre société-Mr Robot [tJaLHsPDuQ4].mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Google
  Duration: 00:09:46.26, start: 0.000000, bitrate: 1204 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 1073 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x555ccbb68140] Invalid stream specifier: '0:a', '0:s'].
    Last message repeated 3 times
Sync stream specification in map ['1:v', '0:a', '0:s'] does not match any streams.
Traceback (most recent call last):
  File "/home/lionel/Git/binary_qrcode_stegano/encrypt.py", line 108, in copy_audio_and_metadata_to_output
    ffmpeg.run(output_stream)
  File "/usr/local/lib/python3.11/dist-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lionel/Git/binary_qrcode_stegano/encrypt.py", line 267, in <module>
    embed_qr_codes_in_video(video_file, binary_file, output_video_file)
  File "/home/lionel/Git/binary_qrcode_stegano/encrypt.py", line 217, in embed_qr_codes_in_video
    copy_audio_and_metadata_to_output(video_file, output_video_file)
  File "/home/lionel/Git/binary_qrcode_stegano/encrypt.py", line 112, in copy_audio_and_metadata_to_output
    print(f"[ERROR] FFmpeg error: {e.stderr.decode()}")
                                   ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by ILPlais** [comment]
Corrected in the 4de69f11def0d0542d326b89a5e5d6f6a8ed5bd8 commit.
